//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_CustomerType
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> CustomerTypeID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual CustomerType CustomerType { get; set; }
    }
}
